name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Server Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            set -e
            
            cd /opt/gem-hub-backend
            
            git fetch origin
            git checkout main
            git pull origin main
            
            chmod +x .deploy/deploy.sh
            ./.deploy/deploy.sh